version: "3"

networks:
  my_network:
    driver: bridge

services:
  keycloak:
    image: jboss/keycloak    
    restart: "no"
    environment:
      - DB_VENDOR=H2      
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=123
    ports:
      - "8080:8080"
    networks:
      - my_network
